[Variables]
;--- Common Settings ---
DefaultWidth=200
DefaultHeight=200

;--- Chibi Image Paths ---
Chibi1Image=#@#cloudMusic.png
Chibi2Image=#@#social-spotify.png
Chibi3Image=#@#PotPlayer.png
Chibi4Image=#@#youtube.png
Chibi5Image=#@#stop.png


;--- Player Paths (用户可修改) ---
CloudMusicPath=C:\Program Files\NetEase\CloudMusic\cloudmusic.exe
PotPlayerPath=C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe
SpotifyPath=C:\Users\Atri\AppData\Roaming\Spotify\Spotify.exe
YouTubePath=https://www.youtube.com

;--- Individual Sizes (override defaults) ---
Chibi1Width=100
Chibi1Height=100
